spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
server:
  servlet:
    jsp:
      init-parameters:
        development: true
jdbc:
  url: jdbc:mysql://119.45.157.172:3306/hispro_lis?useSSL=false
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: zhp!43435438
mybatis:
  mapper-locations: classpath*:cn.o0k.mapper/**/*.xml
  type-aliases-package: cn.o0k.pojo
