spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
server:
  servlet:
    jsp:
      init-parameters:
        development: true
jdbc:
  url: jdbc:mysql://localhost:3306/zhp_schema?useSSL=false&serverTimezone=UTC
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: root
mybatis:
  ## 搜索指定包别名
  typeAliasesPackage: cn.o0k.pojo
  ## 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/zhp/*Mapper.xml
  ## 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
